<a href="https://colab.research.google.com/github/smrutipunto/OPT/blob/main/opt_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#
#Problem 1: Matrix Multiplication
import numpy as np

A = np.array([[2, 3], [4, 5]])
B = np.array([[1, 2], [0, 1]])
C = np.dot(A, B)

print("Matrix Multiplication:\n", C)

Matrix Multiplication:
 [[ 2  7]
 [ 4 13]]


In [ ]:
#Problem 2: Matrix Inversion
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [ ]:
#Problem 3: Determinant of a Matrix
A = np.array([[3, 1], [4, 2]])
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: 2.0


In [ ]:
#Problem 4: Eigenvalues and Eigenvectors
A = np.array([[2, 0], [0, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


In [ ]:
#Problem 5: Rank and Trace
A = np.array([[1, 2], [3, 4]])
rank = np.linalg.matrix_rank(A)
trace = np.trace(A)
print("Rank:", rank)
print("Trace:", trace)

Rank: 2
Trace: 5


In [ ]:
# pip install sympy
from sympy import Matrix, symbols, diff
x1, x2 = symbols('x1 x2')
x = Matrix([x1, x2])

In [ ]:
#Problem 1: Gradient of a Scalar Function
f = x1**2 + 3*x1*x2 + x2**2
grad_f = Matrix([diff(f, var) for var in x])
print("Gradient:\n", grad_f)

Gradient:
 Matrix([[2*x1 + 3*x2], [3*x1 + 2*x2]])


In [ ]:
#Problem 2: Jacobian of a Vector Function
f = Matrix([x1**2 + x2, x1 + x2**2])
J = f.jacobian(x)
print("Jacobian:\n", J)

Jacobian:
 Matrix([[2*x1, 1], [1, 2*x2]])


In [ ]:
#Problem 3: Hessian Matrix
f = x1**2 + x1*x2 + x2**2
H = Matrix([[diff(f, i, j) for j in x] for i in x])
print("Hessian:\n", H)

Hessian:
 Matrix([[2, 1], [1, 2]])


In [ ]:
#Problem 4: Derivative of Quadratic Form
A = Matrix([[2, 1], [1, 3]])
f = (x.T * A * x)[0]
df_dx = Matrix([diff(f, var) for var in x])
print("(xAx):\n", df_dx)

(xAx):
 Matrix([[4*x1 + 2*x2], [2*x1 + 6*x2]])


In [ ]:
# pip install scikit-learn
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [ ]:
# Step 1: Define the Dataset
# House data: [Number of Rooms, Age of House]
X = np.array([
[2, 15],
[3, 10],
[4, 8],
[5, 5],
[6, 3]
])

In [ ]:
# Target: House prices in $1000s
y = np.array([220, 280, 330, 400, 470])

# Step 2: Standardize the Features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
# Step 3: Train the Linear Regression Model
model = LinearRegression()
model.fit(X_scaled, y)

LinearRegression()

In [ ]:
# Step 4: Display Model Parameters
intercept = round(model.intercept_, 2)
coefficients = np.round(model.coef_, 2)

In [ ]:
print("Linear Regression Results:")
print(f"Intercept (): {intercept}")
print(f"Coefficients ( for rooms, for age): {coefficients}")

Linear Regression Results:
Intercept (): 340.0
Coefficients ( for rooms, for age): [99.83 12.35]


In [ ]:
# Step 5: Predict Price for New Example (4 rooms, 6 years old)
new_house = np.array([[4, 6]])
new_house_scaled = scaler.transform(new_house)
predicted_price = model.predict(new_house_scaled)

In [ ]:
print("\n Predicted price for a house with 4 rooms and age 6 years:")
print(f"${predicted_price[0]:,.2f}")


 Predicted price for a house with 4 rooms and age 6 years:
$333.48
